name: Python complaint system
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test123
          POSTGRES_DB: DroneBoxExpressFlaskTest
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies and test
      env:
        DB_USER: postgres
        DB_PASS: test123
        DB_HOST: localhost
        DB_PORT: '5432'
        DB_NAME: 'DroneBoxExpressFlaskTest'
        TEST_DB_NAME: "DroneBoxExpressFlaskTest"
        SECRET_KEY: "123abc"
        CONFIG_ENV: "config.TestingConfig"
        MAILTRAP_API_KEY: ""
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export PGPASSWORD="test123"
        pytest